services:

    _defaults:
        autowire: TRUE
        autoconfigure: TRUE

    Pierotto\SupervisorBundle\Command\SupervisorGeneratorCommand:
        arguments:
            $name: 'supervisor:generate'
            $prefix: '%supervisor.prefix%'
            $programs: '%supervisor.programs%'
            $path: '%kernel.project_dir%/app/config/supervisor.conf'
